### ISSUE TITLE
Event Description Page

### ISSUE THREAD

**Issue by JenniferTjen** [Daggerpov/Spawn-App-iOS-SwiftUI#13]

**Comment by Daggerpov** [comment]
- [ ] Rename `EventView` -> `EventCardView`
- [ ] Navigation button from the event card to this event (click action)
- [ ] pop up a window
    - At first, let's just do a sub-page navigation, then do a proper modal for now
- [ ] Populate the data (pass in the `event` object from the parent, `EventView.swift` file, as well as the `color` Object)
- [ ] Styling the data

NOTE: can split these things into reusable components between `EventCardView.swift` and `EventDescriptionView.swift`

    - [ ] Rounded rectangle around the whole description
    - [ ] Comment adding section
    - [ ] Comment adding button
    - [ ] Like button
    - [ ] Same styling as Event Card for: title, time, and location
- [ ] Turn navigation page into proper modal

**Comment by Daggerpov** [comment]
![Screenshot 2024-11-09 at 3 46 40 PM](https://github.com/user-attachments/assets/307b1870-3181-4818-8140-3a4fdf400879)

**Comment by Daggerpov** [comment]
@JenniferTjen current progress ^^

What's left is all styling

**Comment by Daggerpov** [comment]
https://medium.com/geekculture/swiftui-tutorial-a-simple-interactive-popup-6b9a91c3d057
