### ISSUE TITLE
Event card: Time & Location Styling

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/Spawn-App-iOS-SwiftUI#2]
Requirement: adjust event time & location styling to match Figma design. 

Tech notes: can achieve this using with `RoundedRectangle()` containing shape or `.cornerRadius()` property. 

Expected result (figma drawing):

![Image](https://github.com/user-attachments/assets/00ccd4dd-637f-43ef-af1c-ca93855490f7)

Actual result (current):

**Comment by Daggerpov** [comment]
Current progress, after @miketham24 and @JenniferTjen 's changes, and my additions as well:
<img width="270" alt="image" src="https://github.com/user-attachments/assets/e432b778-72e3-42d1-b2ac-02dfbbedf972">

**Comment by Daggerpov** [comment]
Could definitely make it more like the Figma drawing, but honestly, this looks good enough. Resolving this issue.

**Comment by JenniferTjen** [comment]
what happens when the location text is longer than that?

**Comment by Daggerpov** [comment]
> what happens when the location text is longer than that?

Can test my editing the mock locations in `Event.swift`
